/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /**
         * Create Project
         * @description 音源からプロジェクトを作る（同じ音源のプロジェクトがあればそれ）。analyze なら解析のジョブも始める
         */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__pid__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_projects__pid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Info */
        patch: operations["update_info_api_projects__pid__info_patch"];
        trace?: never;
    };
    "/api/projects/{pid}/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Options */
        patch: operations["update_options_api_projects__pid__options_patch"];
        trace?: never;
    };
    "/api/projects/{pid}/lyrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Lyrics */
        put: operations["set_lyrics_api_projects__pid__lyrics_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/lyrics/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Lyrics
         * @description 歌詞サイトを検索する。title を省けば曲情報から（Project.search_lyrics）
         */
        get: operations["search_lyrics_api_projects__pid__lyrics_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/lyrics/use": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Use Lyrics
         * @description 歌詞ページから歌詞を取って使う（曲情報の空いている項目も埋める）
         */
        post: operations["use_lyrics_api_projects__pid__lyrics_use_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run */
        post: operations["run_api_projects__pid__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Cancel Job */
        delete: operations["cancel_job_api_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/chordpro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chordpro */
        get: operations["get_chordpro_api_projects__pid__chordpro_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audio */
        get: operations["get_audio_api_projects__pid__audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/midi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Midi
         * @description MIDI（edited なら手で直したコードを書き込んだもの）
         */
        get: operations["get_midi_api_projects__pid__midi_get"];
        /**
         * Upload Midi
         * @description 手元の AMT の MIDI を使う（tsumugi を走らせない）
         */
        put: operations["upload_midi_api_projects__pid__midi_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_project_api_projects_post */
        Body_create_project_api_projects_post: {
            /** Audio */
            audio: string;
            /**
             * Analyze
             * @default true
             */
            analyze: boolean;
        };
        /** Body_upload_midi_api_projects__pid__midi_put */
        Body_upload_midi_api_projects__pid__midi_put: {
            /** Midi */
            midi: string;
        };
        /** EditsModel */
        EditsModel: {
            /** Chords */
            chords: boolean;
            /** Alignment */
            alignment: boolean;
            /** Alignment Outdated */
            alignment_outdated: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InfoPatch */
        InfoPatch: {
            /** Title */
            title?: string | null;
            /** Artist */
            artist?: string | null;
            /** Lyricist */
            lyricist?: string | null;
            /** Composer */
            composer?: string | null;
            /** Arranger */
            arranger?: string | null;
        };
        /** JobModel */
        JobModel: {
            /** Id */
            id: string;
            /** Project */
            project: string;
            /** Stages */
            stages: string[];
            /** Force */
            force: boolean;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "done" | "error" | "cancelled";
            /** Stage */
            stage: string | null;
            /** Finished Stages */
            finished_stages: string[];
            /** Error */
            error: string | null;
            /** Log */
            log: string[];
            /** Created */
            created: string;
            /** Started */
            started: string | null;
            /** Finished */
            finished: string | null;
        };
        /** LyricsHit */
        LyricsHit: {
            /** Site */
            site: string;
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /** Url */
            url: string;
            /**
             * Lyricist
             * @default
             */
            lyricist: string;
            /**
             * Composer
             * @default
             */
            composer: string;
            /**
             * Arranger
             * @default
             */
            arranger: string;
            /**
             * Beginning
             * @default
             */
            beginning: string;
        };
        /** LyricsIn */
        LyricsIn: {
            /** Text */
            text: string;
        };
        /**
         * OptionsModel
         * @description Options と RenderOptions の項目（Project.set_options の名前）
         */
        OptionsModel: {
            /**
             * Melody
             * @enum {string}
             */
            melody: "sheetsage" | "amt";
            /**
             * Beats
             * @enum {string}
             */
            beats: "amt" | "sheetsage";
            /** Sheetsage Model */
            sheetsage_model: string;
            /** Melody Prior */
            melody_prior: boolean;
            /** Snap To Notes */
            snap_to_notes: boolean;
            /** Simplify */
            simplify: boolean;
            /**
             * Notation
             * @enum {string}
             */
            notation: "name" | "degree";
            /** Head Outside */
            head_outside: boolean;
            /** Tail Grid */
            tail_grid: boolean;
            /** Min Gap Bars */
            min_gap_bars: number;
            /** Tol */
            tol: number;
            /** Head Window */
            head_window: number;
        };
        /** OptionsPatch */
        OptionsPatch: {
            /** Melody */
            melody?: ("sheetsage" | "amt") | null;
            /** Beats */
            beats?: ("sheetsage" | "amt") | null;
            /** Sheetsage Model */
            sheetsage_model?: string | null;
            /** Melody Prior */
            melody_prior?: boolean | null;
            /** Snap To Notes */
            snap_to_notes?: boolean | null;
            /** Simplify */
            simplify?: boolean | null;
            /** Notation */
            notation?: ("name" | "degree") | null;
            /** Head Outside */
            head_outside?: boolean | null;
            /** Tail Grid */
            tail_grid?: boolean | null;
            /** Min Gap Bars */
            min_gap_bars?: number | null;
            /** Tol */
            tol?: number | null;
            /** Head Window */
            head_window?: number | null;
        };
        /** ProjectDetail */
        ProjectDetail: {
            /** Id */
            id: string;
            /** Created */
            created: string;
            info: components["schemas"]["SongInfoModel"];
            /** Status */
            status: {
                [key: string]: "done" | "stale" | "pending" | "skipped";
            };
            /** Busy */
            busy: boolean;
            /** Audio */
            audio: string;
            /** Sources */
            sources: {
                [key: string]: string;
            };
            /** Alternatives */
            alternatives: string[][];
            /** Lyrics */
            lyrics: string;
            /** Lyrics Source */
            lyrics_source: {
                [key: string]: unknown;
            };
            options: components["schemas"]["OptionsModel"];
            /** Midi Source */
            midi_source: string | null;
            /** Output */
            output: string | null;
            /** Output Version */
            output_version: string | null;
            edits: components["schemas"]["EditsModel"];
            /** Jobs */
            jobs: components["schemas"]["JobModel"][];
        };
        /** ProjectSummary */
        ProjectSummary: {
            /** Id */
            id: string;
            /** Created */
            created: string;
            info: components["schemas"]["SongInfoModel"];
            /** Status */
            status: {
                [key: string]: "done" | "stale" | "pending" | "skipped";
            };
            /** Busy */
            busy: boolean;
        };
        /** RunIn */
        RunIn: {
            /**
             * Stages
             * @default []
             */
            stages: (("midi" | "melody" | "vocals" | "align" | "render") | "analysis")[];
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /** SongInfoModel */
        SongInfoModel: {
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Artist
             * @default
             */
            artist: string;
            /**
             * Lyricist
             * @default
             */
            lyricist: string;
            /**
             * Composer
             * @default
             */
            composer: string;
            /**
             * Arranger
             * @default
             */
            arranger: string;
        };
        /** UseLyricsIn */
        UseLyricsIn: {
            /** Url */
            url: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_project_api_projects_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__pid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__pid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_info_api_projects__pid__info_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InfoPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_options_api_projects__pid__options_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptionsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_lyrics_api_projects__pid__lyrics_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LyricsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_lyrics_api_projects__pid__lyrics_search_get: {
        parameters: {
            query?: {
                title?: string | null;
                artist?: string;
            };
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LyricsHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    use_lyrics_api_projects__pid__lyrics_use_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UseLyricsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_api_projects__pid__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                project?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chordpro_api_projects__pid__chordpro_get: {
        parameters: {
            query?: {
                download?: boolean;
            };
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audio_api_projects__pid__audio_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_midi_api_projects__pid__midi_get: {
        parameters: {
            query?: {
                edited?: boolean;
            };
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_midi_api_projects__pid__midi_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_midi_api_projects__pid__midi_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
